### ISSUE TITLE
Add WAV-IMA/ADPCM support

### ISSUE THREAD

**Issue by r-lyeh** [ddiakopoulos/libnyquist#11]
ADPCM is extremely helpful when streaming hundred of megabytes from disk.
`mmap()`-ing wav files from disk, then decoding adpcm on the fly is one of the cheapest solutions, specially for mobile devices.

The source (MIT license) for a IMA/ADPCM decoder can be found here:
https://github.com/afterwise/aw-ima/

**Comment by r-lyeh** [comment]
zlib licensed,
https://github.com/stuffmatic/kowalski/blob/master/src/engine/kwl_decoder_imaadpcm.c

**Comment by ddiakopoulos** [comment]
This is now sitting in a branch https://github.com/ddiakopoulos/libnyquist/tree/adpcm but there's a weird issue I need to track down. It's randomly clipping things when it shouldn't. Also, this decoder will become most useful when libnyquist implements streaming support.

**Comment by r-lyeh** [comment]
:+1: what adpcm variant is it?

**Comment by ddiakopoulos** [comment]
IMA-ADPCM (IMA4). This impl is currently working with encoder in Reaper and Audacity. Need to work on my CAF/AIFF decoder (I added a test IMA CAF file to the repo), but that should work transparently once it's online.

**Comment by ddiakopoulos** [comment]
Sweet! Closing this out. Implementation is fixed and now on master.

**Comment by r-lyeh** [comment]
:smiley:
