### ISSUE TITLE
mpc mono crash

### ISSUE THREAD

**Issue by r-lyeh** [ddiakopoulos/libnyquist#13]
Hey there,

Just giving a try on the library. 
Nice work so far!

It seems to crash here with `test_data\ad_hoc\44_16_mono.mpc`. Stereo mpc is fine though.
Does it work on your machine :tm: ? :)

**Comment by ddiakopoulos** [comment]
Hmm. With what compiler? I just tried in XCode 7 + VS 2015 and the mono mpc file was ok.

**Comment by r-lyeh** [comment]
vs2013, but I was using my own build script. I'll trace the crash and let you know!

**Comment by r-lyeh** [comment]
Aha well, it is a heap corruption issue (probably when inflating `d->samples` during `mpc_demux_decode`) and it only happens in 64-bit builds. More info soon

**Comment by ddiakopoulos** [comment]
Investigated for 45 mins this morning with no luck. Probably an off by one error will reveal itself after 20 hours of debugging.

**Comment by ddiakopoulos** [comment]
Let me know if 031d94497b07f8195cc6e26be9e327c3d0fcd42f fixes it for you

**Comment by r-lyeh** [comment]
woohoo :D perfect!
