### ISSUE TITLE
AudioDevice imposes RtAudio dependency

### ISSUE THREAD

**Issue by meshula** [ddiakopoulos/libnyquist#17]
I was pointing someone at libnyquist, but they objected due to needing to link WMF or CoreAudio. I think that comes from the AudioDevice dependency on RtAudio?

I think AudioDevice should be reserved for the examples and tests, but not be in the library itself, as it isn't used anywhere else in the codecs?

**Comment by ddiakopoulos** [comment]
Yeah! Good catch, I 100% agree. I can fix it :)

**Comment by ddiakopoulos** [comment]
Should be fixed in 77938cd0be8a1d724457ec900dfc4e58015d00fa

**Comment by meshula** [comment]
Thanks!
