### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by sevagh** [ddiakopoulos/libnyquist#37]
Hello,

I'm using libnyquist for a pitch tracking application. I decode the audio from a wav file, and run it through some algorithms (Mcleod, YIN, etc.)

For a few minutes I was scratching my head about why I was getting completely wrong results until I noticed the `normalized between [-1.0, 1.0]` part of the README. When I multiply the `samples` vector output by the decoder by a constant e.g. `100` or `1000` to amplify the signal, my pitch tracking algorithms produce correct results.

My question is,

* Is my approach correct? This decoder library outputting normalized audio data and clients multiplying the vector by a scalar factor to amplify it? Does that introduce any problems, is there a better way for me to achieve that? Modify my pitch tracking code to operate on normalized values?
* Could that behavior be modified in this library? Or is normalized output always desired/mandatory

**Comment by ddiakopoulos** [comment]
Hi @sevagh - I think that must be a bug in your pitch detection pipeline! Normalized floating point values are quite frequent in audio systems, and many audio APIs will hard clip values over the -1 to 1 range. I'm closing this issue for now but feel free to chime in again if you uncover any mysteries in your code :)
