### ISSUE TITLE
Memory leak when decoding mp3 file fix uses incorrect method to free memory.

### ISSUE THREAD

**Issue by phniix** [ddiakopoulos/libnyquist#54]
The most excellent memory leak find in https://github.com/ddiakopoulos/libnyquist/pull/48 has used the incorrect function to free the memory.

Taking a look at minimp3, https://github.com/ddiakopoulos/libnyquist/blob/244afdd52e8fc5bc0396cbcd9437b2d74271509f/third_party/minimp3/minimp3_ex.h#L408 we observe that `malloc()` was used to allocate the memory. The function used to remove the memory should be `free()` and not `delete`.

**Comment by ddiakopoulos** [comment]
Thanks for the fix @phniix !

**Comment by phniix** [comment]
No dramas at all! :D
