### ISSUE TITLE
Add Musepack support

### ISSUE THREAD

**Issue by r-lyeh** [ddiakopoulos/libnyquist#9]
Hey there,

Nice lib you have in here :)
Please consider musepack decoding as it is very cheap to decode for mobile devices.
Also, license is bsd-3.

Original source download at: 
https://www.musepack.net/index.php?pg=src (see sv8 download, libmpcdec/ subfolder)

Totally optional, I hacked a mpc decoder if you need some guidance (which I doubt :)
https://github.com/r-lyeh/wave/blob/master/wave.cpp#L17

**Comment by ddiakopoulos** [comment]
Yes! This looks quite straightforward. I'll add in a backend for mpc soon.

**Comment by ddiakopoulos** [comment]
Done! Implemented in #dd97514f82918787f9aa49e3332d7b54a33b0ed6 
@r-lyeh I used your little ref impl for reading from memory :)

**Comment by r-lyeh** [comment]
awesome :) thx!
